name: Generate Homepage Screenshot
on: ['workflow_dispatch']

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master # Required for headful puppeteer
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://jack.mawer.uk
        fullPage: true
        type: png
        noCommitHashFileName: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: screenshot
